/**
 * generated by node,/home/paul/vows-skelgen/skelgen.js,priceUtils.js,--output,test2.js
 * https://github.com/pauly/vows-skelgen
 * Fri Aug 23 2013 11:52:46 GMT+0000 (UTC)
 */

var assert = require( 'assert' );
var vows = require( 'vows' );
var file = './priceUtils.js';
var priceUtils = require( file );

vows.describe( 'priceUtils' ).addBatch( {
  'priceUtils.getDiscount': {
    'handles malformed input': function ( ) {
      assert.doesNotThrow(
        function ( ) {
          priceUtils.getDiscount( 'foo' );
          priceUtils.getDiscount( 66 );
          priceUtils.getDiscount( undefined );
          priceUtils.getDiscount( null );
          priceUtils.getDiscount( [] );
          priceUtils.getDiscount( {} );
          priceUtils.getDiscount( new Date( ) );
          priceUtils.getDiscount( 'function ( ) { }' );
        }
      );
    }
  }
} ).run( );
