'use strict'
/**
 * generated by /Users/paulclarke/.nvm/versions/node/v10.22.0/bin/node,/Users/paulclarke/sites/js-skelgen/skelgen.js,demo/priceUtils.js,--method,getDiscount,--output,demo/test2.js
 * https://github.com/pauly/vows-skelgen
 * Sat Jan 09 2021 17:46:03 GMT+0000 (Coordinated Universal Time)
 */

const expect = require('chai').use(require('dirty-chai')).expect
const file = './priceUtils.js'
const priceUtils = require(file)

describe('priceUtils.js', function () {
  describe('priceUtils.getDiscount', function () {
    it('handles good input', function () {
      expect(priceUtils.getDiscount({ price: 1000 })).to.deep.equal(null) // goodInputTests
      expect(priceUtils.getDiscount({ price: 900, discount: { originalPrice: 1000 } })).to.deep.equal(100) // goodInputTests
    })
    it('handles malformed input', function () {
      expect(function () {
        priceUtils.getDiscount(66)
        priceUtils.getDiscount(null)
        priceUtils.getDiscount([])
        priceUtils.getDiscount({})
      }).not.to.throw()
    })
  })
})
